/* minimal runnable v7.2 package */
const elAreas=document.getElementById('areas');const elLineFilter=document.getElementById('lineFilter');const elQ=document.getElementById('q');const elOnlyLate=document.getElementById('onlyLate');const btnFgr=document.getElementById('btnFgr');const btnAsm=document.getElementById('btnAsm');const btnAll=document.getElementById('btnAll');const tplArea=document.getElementById('tplArea');const tplItem=document.getElementById('tplItem');const storeKey='skf.fiveS.v7.2.demo';
const VOC_1S=['Zona pedonale pavimento','Zona di lavoro (pavimento, macchina)','Materiali','Informazioni','Processo di etichettatura'];
const VOC_2S=['Sicurezza','Qualità','Posizione Pre-Fissate','Documenti','Concetti'];
const VOC_3S=['Pulizia','Misure preventive','La pulizia è di routine e esiste un piano per un risultato duraturo'];
const VOC_4S=['Aree di  passaggio','Area di lavoro','Materiali','Informazione','Visual Management'];
const VOC_5S=['Piano per sostenere il risultato','Piano per risultati duraturi','Coinvolgimento dei membri del team'];
function makeArea(line,sector){const map=l=>l.map(t=>({t,p:0,note:'',resp:'',due:''}));return{line,sector,S:{'1S':map(VOC_1S),'2S':map(VOC_2S),'3S':map(VOC_3S),'4S':map(VOC_4S),'5S':map(VOC_5S)}}}
let state=(()=>{try{const raw=localStorage.getItem(storeKey);return raw?JSON.parse(raw):{areas:[makeArea('L2','Rettifica')]}}catch(e){return{areas:[makeArea('L2','Rettifica')]}}})();save();
let ui={q:'',line:'ALL',sector:'ALL',onlyLate:false};
function save(){localStorage.setItem(storeKey,JSON.stringify(state));}
function filtered(){return state.areas;}
function render(){elAreas.innerHTML='';filtered().forEach((a,idx)=>{const node=tplArea.content.firstElementChild.cloneNode(true);const line=node.querySelector('.area-line');line.value=a.line;node.querySelectorAll('.panel').forEach(p=>{const s=p.dataset.s;(a.S[s]||[]).forEach((it,i)=>{const n=tplItem.content.firstElementChild.cloneNode(true);n.querySelector('.txt').value=it.t;n.querySelector('.points').value=String(it.p||0);p.appendChild(n);});});node.querySelector('.add-item').addEventListener('click',()=>{const s=node.querySelector('.tab.active').dataset.s;state.areas[idx].S[s].push({t:'',p:0,note:'',resp:'',due:''});save();render();});node.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{node.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');node.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.s===tab.dataset.s));}));elAreas.appendChild(node);});}
render();
document.getElementById('btnNewArea').addEventListener('click',()=>{const line=(prompt('Linea nuova?','L3')||'Lx').trim();state.areas.push(makeArea(line,'Rettifica'));save();render();});
document.getElementById('btnExport').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='SKF_5S.json';a.click();});document.getElementById('fileImport').addEventListener('change',async(e)=>{const f=e.target.files[0];if(!f)return;state=JSON.parse(await f.text());save();render();});