
const KEY='skf5s_supervisor_demo';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{"channels":{}}')}catch{return {channels:{}}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function n(x){return typeof x==='number'?x:parseFloat(String(x||'0').replace('%',''))||0}
function norm(r){const p=r.points||{};return {area:r.area||'',channel:r.channel||r.CH||'CH',date:r.date||new Date().toISOString().slice(0,10),points:{s1:n(p.s1),s2:n(p.s2),s3:n(p.s3),s4:n(p.s4),s5:n(p.s5)},notes:r.notes||[],late:r.late||0}}
function upsert(s,rec){const k=rec.channel;const e=s.channels[k]||{history:[],last:rec};e.last=rec;e.history.push(rec);s.channels[k]=e}
async function handleImport(files){const s=load();let c=0;for(const f of files){try{const arr=JSON.parse(await f.text());(Array.isArray(arr)?arr:[arr]).forEach(r=>{upsert(s,norm(r));c++})}catch(e){console.warn(e)}}save(s);alert('Import completato: '+c+' record');if(document.getElementById('charts')) populateHome(); if(document.getElementById('ch-list')) loadChecklist();}
function renderChart(el,pts){const colors=['#7c3aed','#ef4444','#f59e0b','#10b981','#3b82f6'];const labels=['1S','2S','3S','4S','5S'];el.innerHTML='';const w=document.createElement('div');w.className='bars';[pts.s1,pts.s2,pts.s3,pts.s4,pts.s5].forEach((v,i)=>{const b=document.createElement('div');b.className='bar';b.style.background=colors[i];b.style.height=Math.max(3,Math.min(100,v))+'%';b.dataset.lbl=labels[i];w.appendChild(b)});el.appendChild(w)}
function populateHome(){const s=load();const charts=document.getElementById('charts');charts.innerHTML='';const keys=Object.keys(s.channels);if(keys.length===0){charts.innerHTML='<div class=card>Nessun dato importato.</div>';return}keys.forEach(k=>{const box=document.createElement('div');box.className='chart';box.innerHTML='<div class=row><div><strong>'+k+'</strong><div class=tag>'+s.channels[k].last.area+'</div></div><div><a class=btn href=\'checklist.html#'+encodeURIComponent(k)+'\'>Apri in checklist</a></div></div>';const g=document.createElement('div');box.appendChild(g);renderChart(g,s.channels[k].last.points);charts.appendChild(box)})}
function loadChecklist(){const s=load();const root=document.getElementById('ch-list');root.innerHTML='';const target=decodeURIComponent(location.hash.slice(1)||'');const ch=Object.entries(s.channels).filter(([k])=>!target||k===target);if(ch.length===0){root.innerHTML='<div class=card>Importa prima dei file nella Home.</div>';return}ch.forEach(([k,v])=>{const card=document.createElement('div');card.className='ch-card';card.innerHTML='<div class=row><div class=section-title><span class=tag>'+v.last.area+'</span> '+k+'</div><label class=btn for=imp2>Importa</label></div><div contenteditable=true style="border:1px solid #e5e7eb;border-radius:.5rem;padding:.6rem">Scrivi qui…</div>';root.appendChild(card)})}
function toggleLock(){document.body.classList.toggle('locked');document.getElementById('lockBtn').textContent=document.body.classList.contains('locked')?'Sblocca':'Blocca'}
function populateNotes(){const s=load();const list=document.getElementById('note-list');let items=[];Object.entries(s.channels).forEach(([k,v])=>{v.history.forEach(rec=>{(rec.notes||[]).forEach(n=>items.push({ch:k,area:rec.area,s:n.s||'',date:n.date,text:n.text||'',late:!!n.late}))})});items.sort((a,b)=>a.date<b.date?1:-1);list.innerHTML=items.map(it=>'<div class=ch-card><div class=tag>'+it.area+'</div> <b>'+it.ch+'</b> <span class=tag>'+(it.s||'—')+'</span><div class=small>'+it.date+'</div><div>'+it.text.replace(/</g,'&lt;')+'</div></div>').join('')||'<div class=card>Nessuna nota.</div>'}
window.SKF5S={handleImport,populateHome,loadChecklist,toggleLock,populateNotes};
